format = """
╭ $all${custom.git_scope}$fill$kubernetes${custom.drconfig}\
$line_break\
╰─$jobs\
$battery\
$container\
$shell\
$status\
$character"""

right_format = """
$time\
$shlvl"""

[time]
# what time is it?
disabled = true

[username]
# who am I?
show_always = false

[shell]
# am I in a shell that isn't zsh?
zsh_indicator = ""
disabled = false

[direnv]
# what's my direnv status?
disabled = false
symbol = " "
allowed_msg = "a"
not_allowed_msg = "na"
denied_msg = "x"
loaded_msg = "l"
unloaded_msg = "u"

[shlvl]
# how many shell levels deep am I?
disabled = false
symbol = " "

[status]
disabled = false

[git_status]
# I've disabled git_status because it's slow for large repos, like the monorepo
# at work. I'd love to be able to disable it conditionally, but that does not
# exist in starship right now.
disabled = true

[git_metrics]
disabled = false

[git_branch]
ignore_branches = ['master', 'main']

[hostname]
# if I'm on SSH, what's my hostname?
ssh_only = true

[localip]
# if I'm on SSH, what's my local IP address?
disabled = false
ssh_only = true

[kubernetes]
# am I in a Kubernetes cluster?
disabled = false
# but only if any of the following conditions are met
detect_files = ["Tiltfile"]
detect_folders = ["charts"]

[[battery.display]]
# when the battery is at 10%, display the icon in red
threshold = 10
style = "bold red"

[[battery.display]]
# when the battery is at 30%, display the icon in yellow
threshold = 30
style = "bold yellow"

[custom.drconfig]
# quickly show the datarobot endpoint from drconfig.yaml
# 🤖 / robot face / U+1F916 / Apple Color Emoji required
# 󱜙 / md-robot_happy / U+F1719 / Nerd Font required
# 🗿 / moyai / U+1F5FF / Apple Color Emoji required
# 👾 / alien_monster / U+1F47E / Apple Color Emoji required
command = "yq '.endpoint' ~/.config/datarobot/drconfig.yaml | awk -F'/api/v2' '{print $1}' | awk -F'//' '{print $2}' | sed 's/datarobot.com/dr/g'"
format = "👾 $output"
description = "The contents of drconfig.yaml"
shell = ["dash", "-eu"]
when = "test -e ~/.config/datarobot/drconfig.yaml && command -v yq"

[custom.git_scope]
# https://github.com/starship/starship/discussions/1252#discussioncomment-2461567
command = '''
printf "%s (%s)" \
  "$(if [ -n "$GIT_AUTHOR_EMAIL" ]; then echo "$GIT_AUTHOR_EMAIL"; else git config --get user.email; fi)" \
  "$(if [ -n "$GIT_AUTHOR_NAME" ]; then echo "$GIT_AUTHOR_NAME"; else git config --get user.name; fi)"
'''
description = 'The currently configured Git user.{email,name}'
format = 'as [$output]($style) '
style = 'blue bold'
shell = ["dash", "-e"]
when = 'git rev-parse --is-inside-work-tree'
